FROM python:slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY Frontend .

EXPOSE 8001

CMD ["uvicorn", "Web.Server:app", "--host", "0.0.0.0", "--port", "8001"]